#!/bin/bash

# This script requires that `swift-format` is installed using `build-dependendencies`. It also provides the `--ci` flag which runs `swift-format` how it would be run in CI

PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd "$(git rev-parse --show-toplevel)" && pwd )"

function swift-format() {
  if [[ -z "$DEPENDENCIES_ROOT" ]]; then 
    "$PROJECT_ROOT/.dependencies/installed/tools/swift-format" $@
  else 
    "$DEPENDENCIES_ROOT/installed/tools/swift-format" $@
  fi
}

if [[ "$1" == "--ci" ]]; then
  if [[ "$#" != "1" ]]; then
    echo "--ci cannot be used with any other arguments" 1>&2
    exit 1
  fi
  swift-format --mode format --in-place --recursive Sources Tests
else
  swift-format $@
fi
